services:
  mysql:
    container_name: mysql-db
    image: mysql:8.3
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: myPassword
      MYSQL_DATABASE: clean_database

  app:
    build: .
    depends_on:
      - mysql
